### ISSUE TITLE
Nicer agent and destination sprites

### ISSUE THREAD

**Issue by LiquidityC** [Oliveshark/Pathworks#23]
As the title suggests. The ugly sprites i threw together in 2 minutes to represent an agent and it's destination are pretty hideous.

So anyone with a more artistic eye are welcome to submit some new tiles.

The agent and destination should be stored in 2 separate 32x32 size png files.

**Note:** The program 'tints' agents and destinations with it's randomized color. White colors in the original sprite will have the clearest representation of the tint color. This is something to take into account when designing new sprites.

This issue will not be closed upon first submission. If there are many choices we'll implement some solution where you can 'change' sprite during runtime.

**Comment by mast4461** [comment]
(Adding some links to help other newcomers)

The sprites are located in [core/assets](https://github.com/Oliveshark/Pathworks/tree/master/core/assets).

Agent sprite file: [link](https://github.com/Oliveshark/Pathworks/blob/master/core/assets/agent.png)
View raw: [link](https://raw.githubusercontent.com/Oliveshark/Pathworks/master/core/assets/agent.png)

Destination sprite file: [link](https://github.com/Oliveshark/Pathworks/blob/master/core/assets/destination.png)
View raw: [link](https://raw.githubusercontent.com/Oliveshark/Pathworks/master/core/assets/destination.png)
